# Change these first
owner: berlinserver # Your GitHub organization or username, where this repository lives
repo: estatus # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: DAP Website
    url: http://web.ula.ve/dap/
  - name: SIDAP PROFESORES
    url: http://uladap.adm.ula.ve/sidap/pdi
  - name: SIDAP
    url: http://uladap.adm.ula.ve/sidap/
  - name: SIDAP RED
    url: http://190.168.72.22/sidap/
  - name: WEB PRINCIPAL DAP
    url: https://dap.ula.ve
  - name: DAP INTERNACIONAL EEUU
    url: https://dapenlinea.ula.ve
  - name: ENLACE EXTERNO DAP
    url: http://sistemasdap.ula.ve/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /estatus
  cname: t1.dapenlinea.com
  logoUrl: https://berlinserver.github.io/IconWhite.png
  theme: light
  name: DAPLive
  introTitle: "**DAPLive**"
  introMessage: Estado en VIVO de los Servidores de la Direccion de Asuntos Profesorales, Universidad de los Andes. Merida, Venezuela 5101
  navbar:
    - title: Status
      href: /
    - title: Source
      href: https://github.com/$OWNER/$REPO
i18n:
  activeIncidents: Incidentes activos
  footer: Hola! esta website es propiedad de [DAP-ULA-VE](http://web.ula.ve/dap/), creada y monitoreada por [Unidad Operativa de Sistemas de Informacion](http://web.ula.ve/dap/)
  liveStatus: Estado de los Sistemas en VIVO
  up: Funcionando (OK)
  down: Caida (Error)
  degraded: Lentitud (Alerta)
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1a
  durationAll: Todo
  pastIncidents: Incidentes pasados
  incidentBack: ← Regresar a todos los Incidentes
  allSystemsOperational: Todos los Sistemas están Funcionando Correctamente
  incidentReport: "Incidente #$NUMBER reporte →"
  incidentFixed: Corregido
  incidentOngoing: Incidente en Curso
  incidentOpenedAt: Incidente Iniciado
  incidentClosedAt: Incidente Finalizado
  incidentViewOnGitHub: Ver detalle
  incidentCommentSummary: Actualizado al $DATE por $AUTHOR
  overallUptime: "% de Tiempo en linea: $UPTIME"
  overallUptimeTitle: Tiempo en linea (%)
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Respuesta promedio
  sevelDayResponseTime: Tiempo de respuesta de 7 días
  responseTimeMs: Tiempo de Respuesta (ms)
  pastIncidentsResolved: Corregido en $MINUTES minutos con $POSTS posts

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
